version: '3.4'

services:
  msa.comm.lab.services.order:
    image: ${DOCKER_REGISTRY-}msacommlabservicesorder
    build:
      context: .
      dockerfile: Msa.Comm.Lab.Services.Order/Dockerfile

  msa.comm.lab.services.catalog:
    image: ${DOCKER_REGISTRY-}msacommlabservicescatalog
    build:
      context: .
      dockerfile: Msa.Comm.Lab.Services.Catalog/Dockerfile

